[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm-10_x']

[phases.install]
cmds = ['npm ci --omit=dev --no-audit --no-fund']

[phases.build]
cmds = ['echo "No build step required"']

[phases.start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'